; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[platformio]
;default_envs = dfrobot_firebeetle2_esp32e
; default_envs = firebeetle32
default_envs = seeed

; default options for each '[env:**]'
[env]
platform = espressif32 @ 6.13.0
framework = arduino
board_build.filesystem = littlefs
build_unflags = '-std=gnu++11'
build_flags = 
    -Wall
    -std=gnu++17
    -I.
    -DTARGET_ESP32
    -DTARGET_LARGE_MEMORY
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCONFIG_FREERTOS_WATCHDOG_TIMEOUT_S=120
    -DE2741QS0B3
    -DSEEED_GFX
    #-DUSE_TTF_ICONS

lib_deps = 
    SPI
    Wire
    FS
    SPIFFS
    LittleFS
;    DrawOwm=https://github.com/skiphansen/libDrawOWM
	DrawOwm=symlink://../../../libDrawOWM
    Seeed_GFX=symlink://../../
    bblanchon/ArduinoJson
    truetype

# Enable the backtrace decoder filter
monitor_filters = esp32_exception_decoder

# Optional: Add debug symbols to get exact line numbers
build_type = debug

[env:seeed]
board = seeed_xiao_esp32s3
monitor_speed = 115200
upload_port = /dev/ttyACM0

