#!/usr/bin/env python3

# Generated by Google AI mode
# prompt: renumber codepoints in ttf file python

from fontTools.ttLib import TTFont

def remap_codepoints(font_path, mapping, output_path):
    # Load the font
    font = TTFont(font_path)
    
    # Access the cmap (Character Map) table
    cmap = font['cmap']
    
    # Iterate through all subtables (Platform/Encoding variants)
    for table in cmap.tables:
        # Create a new dictionary to avoid modifying the table while iterating
        new_cmap = {}
        
        for old_codepoint, glyph_name in table.cmap.items():
            if old_codepoint in mapping:
                new_codepoint = mapping[old_codepoint]
                #print(f'0x{old_codepoint:x} -> 0x{new_codepoint:x}')
                new_cmap[new_codepoint] = glyph_name
            else:
                # Keep original mapping if no renumber rule is provided
                new_cmap[old_codepoint] = glyph_name
                
        # Apply the updated mapping
        table.cmap = new_cmap
        
    # Save the modified font
    font.save(output_path)
    print(f"Font saved to {output_path}")

utf82unicode = {}
undefined = 0

print(f'Note: 5 expected code points expected')

for byte_value in range(0x80, 0xbf):
    try:
        # Convert single byte to character
        char = bytes([byte_value]).decode('windows-1252')
        code_point = ord(char)
        #print(f"Byte 0x{byte_value:02X} -> Unicode U+{code_point:04X} ({char})")
        utf82unicode[code_point] = byte_value
    except UnicodeDecodeError:
        # Catching the 5 undefined Microsoft bytes
        print(f"Byte 0x{byte_value:02X} -> Undefined / Unmapped")
        undefined += 1

if undefined == 5:
    print(f'{undefined} code points, as expected')
else:
    print(f'Error: {undefined} code points, 5 expected')
#print(f'Reverse map: {reverse_map}')


remap_codepoints('FreeSans_subset.otf',utf82unicode,'FreeSans_utf8.ttf')


